version: "3.3"

services:
  db_central:
    image: mysql:5.6
    env_file:
      - db.env
    ports:
      - "3307:3306"

  db_remote:
    image: mysql:5.6
    environment:
      - db.env
    ports:
      - "3308:3306"
    volumes:
      - ./remote-my.cnf:/etc/mysql/my.cnf

  openmrs-central:
    image: tomcat:8.5.65-jdk8-openjdk-slim
    depends_on:
      - db_central
    volumes:
      - ./openmrs.war:/usr/local/tomcat/webapps/openmrs.war
      - ./central-runtime.properties:/root/.OpenMRS/openmrs-runtime.properties
      - ./modules:/root/.OpenMRS/modules
    ports:
      - "8081:8080"

  openmrs-remote:
    image: tomcat:8.5.65-jdk8-openjdk-slim
    depends_on:
      - db_remote
    volumes:
      - ./openmrs.war:/usr/local/tomcat/webapps/openmrs.war
      - ./remote-runtime.properties:/root/.OpenMRS/openmrs-runtime.properties
      - ./modules:/root/.OpenMRS/modules
    ports:
      - "8082:8080"