version: "3.3"

services:
  mysql-central:
    image: mysql:5.6
    container_name: mysql-central
    env_file:
      - db.env
    ports:
      - "3307:3306"
    volumes:
      - ./central-my.cnf:/etc/mysql/my.cnf
      - ./openmrs.sql:/docker-entrypoint-initdb.d/openmrs.sql

  mysql-remote:
    image: mysql:5.6
    container_name: mysql-remote
    env_file:
      - db.env
    ports:
      - "3308:3306"
    volumes:
      - ./remote-my.cnf:/etc/mysql/my.cnf
      - ./openmrs.sql:/docker-entrypoint-initdb.d/openmrs.sql

  artemis:
    image: cnocorch/activemq-artemis
    container_name: artemis
    ports:
      - "61616:61616"
      - "8161:8161"
    volumes:
      - ./artemis-roles.properties:/var/lib/artemis/etc/artemis-roles.properties
      - ./artemis-users.properties:/var/lib/artemis/etc/artemis-users.properties

  openmrs-central:
    image: tomcat:7.0.109-jdk8-openjdk-slim
    container_name: openmrs-central
    depends_on:
      - mysql-central
      - artemis
    volumes:
      - ./openmrs.war:/usr/local/tomcat/webapps/openmrs.war
      - ./central-runtime.properties:/root/.OpenMRS/openmrs-runtime.properties
      - ./modules:/root/.OpenMRS/modules
    ports:
      - "8081:8080"

  openmrs-remote:
    image: tomcat:7.0.109-jdk8-openjdk-slim
    container_name: openmrs-remote
    depends_on:
      - mysql-remote
      - artemis
    volumes:
      - ./openmrs.war:/usr/local/tomcat/webapps/openmrs.war
      - ./remote-runtime.properties:/root/.OpenMRS/openmrs-runtime.properties
      - ./modules:/root/.OpenMRS/modules
    ports:
      - "8082:8080"